version: '3.8'

services:
  db:
    image: clickhouse:25.3.2.39-jammy
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-initdb:/docker-entrypoint-initdb.d
#    ports:
#      - "9000:9000" # Native client port
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_DB: logger
      CLICKHOUSE_USER: test
      CLICKHOUSE_PASSWORD: test
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:5000" # Flask default port
    environment:
      CHDB_HOST: db
      CHDB_PORT: 9000
      CHDB_DATABASE: logger
      CHDB_USER: test
      CHDB_PASSWORD: test

volumes:
  clickhouse_data: